<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Authors>ACSA</Authors>
    <Product>MarkItDown.Net</Product>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>
